---
- name: copy s3cfg template
  template:
    src: roles/s3/templates/s3cfg.j2
    dest: /home/backups/.s3cfg
    owner: backups
    group: backups
    mode: 0600

- name: copy s3_backup_script.sh.j2
  template:
    src: roles/s3/templates/s3_backup_script.sh.j2
    dest: /home/backups/s3_backup_script.sh
    owner: backups
    group: backups
    mode: 0755
