---
- name: copy apache templates over
  template:
    src: roles/varnish/templates/httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
    owner: root
    group: root
    mode: 0644

- name: copy apache templates over for specific site configuration
  templates:
    src: roles/varnish/templates/website_name.conf.j2
    dest: /etc/httpd/conf.d/{{ website_name }}.conf
    owner: root
    group: root
    mode: 0644
  notify: restart httpd
