---
- name: copy nginx config template
  template:
    src: roles/ssl/templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644

- name: copy varnish.params template
  template:
    src: roles/ssl/templates/varnish.params.j2
    dest: /etc/varnish/varnish.params
    owner: root
    group: root
    mode: 0644

- name: copy website.vcl template
  template:
    src: roles/ssl/templates/website.vcl.j2
    dest: /etc/varnish/{{ website }}.vcl
    owner: root
    group: root
    mode: 0644
  notify: restart varnish

- name: copy wp-config.php template
  template:
    src: roles/ssl/templates/wp-config.php.j2
    dest: /var/www/{{ website }}/public_html/wp-config.php
    owner: root
    group: root
    mode: 0644
  notify: restart nginx 
