---
- stat: path=/etc/letsencrypt
  register: letsencrypt

- name: generate certificate
  shell: certbot certonly --non-interactive --agree-tos --email {{ email }} -d staging.{{ website }}.com --webroot -w /var/www/{{ website }}/public_html --staging
  when: not letsencrypt.stat.exists
