---
- name: Provisioning
  hosts: webservers
  remote_user: root

  tasks:
        - name: Install Packages
          yum: name={{ item }}
          with_items:
            - httpd
            - mariadb-server
            - mariadb
            - php
            - php-mysql
            - php-gd
            - python-dateutil
            - unzip
            - MySQL-python

        - name: Start Apache
          service: name=httpd state=started enabled=yes

        - name: Start MySQL
          service: name=mariadb state=started enabled=yes

        - name: Open port 80
          firewalld: port=80/tcp permanent=yes state=enabled

        - name: http settings
          firewalld: service=http permanent=yes state=enabled

        - name: https settings
          firewalld: service=https permanent=yes state=enabled

        - name: Open port 3306
          firewalld: port=3306/tcp permanent=yes state=enabled
          notify: restart firewalld

        - name: Download S3cmd
          get_url:
            url: https://github.com/s3tools/s3cmd/archive/v1.6.1.tar.gz
            dest: /home

        - unarchive: src=/home/s3cmd-1.6.1.tar.gz dest=/opt copy=no remote_src=yes

        - name: Download wp-cli
          get_url:
            url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
            dest: /home

        - file: path=/home/wp-cli.phar state=touch mode=0755


#MySQL Secure Installation - requires MySQL-python package

        - name: incude variables
          include_vars: vars.yml

        - name: Delete anonymous users for ansible
          action: mysql_user user="" host="{{ ansible_hostname }}" state="absent"

        - name: Delete anonymous users
          action: mysql_user user="" state="absent"

        - name: Remove test database
          action: mysql_db db=test state=absent

        - name: Set MySQL Root Password
          mysql_user: name=root host={{ item }} password={{ mysql_root_password }} state=present
          with_items:
            - 127.0.0.1
            - ::1
            - localhost

        - name: Create backup user
          user: name=backups password={{ password }} shell=/bin/bash home=/home/backups

        - name: Copy rpm file for boto dependencies
          get_url:
            url: http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-8.noarch.rpm
            dest: /tmp

        - name: Install rpm file
          yum:
            name: /tmp/epel-release-7-8.noarch.rpm
            state: present

        - name: Install pip
          yum: name=python-pip

        - name: Install boto with python-pip
          pip: name=boto

#boto required to use S3 module
        - name: Download files from s3
          s3: bucket={{ bucket_name }} access_key={{ access_key }} secret_key={{ secret_key }} object={{ object_name }} dest=/root mode=get


  handlers:
        - name: Reload Apache
          service: name=httpd state=reloaded

        - name: Restart firewalld
          service: name=firewalld state=restarted
