---
- name: Provisioning
  hosts: webservers
  remote_user: root

  tasks:
        - name: Install Apache
          yum: name=httpd state=present

        - name: Start Apache
          service: name=httpd state=started enabled=yes

        - name: Install MySQL-Server
          yum: name=mariadb-server state=present

        - name: Install MySQL
          yum: name=mariadb state=present

        - name: Start MySQL
          service: name=mariadb state=started enabled=yes

        - name: Install PHP
          yum: name=php state=present

        - name: Install PHP-MySQL
          yum: name=php-mysql state=present

        - name: Install PHP-GD
          yum: name=php-gd state=present

        - name: Install Python Date Util
          yum: name=python-dateutil state=present

        - name: Open port 80
          firewalld: port=80/tcp permanent=yes state=enabled

        - name: http settings
          firewalld: service=http permanent=yes state=enabled

        - name: https settings
          firewalld: service=https permanent=yes state=enabled

        - name: Open port 3306
          firewalld: port=3306/tcp permanent=yes state=enabled
          notify: restart firewalld


  handlers:
        - name: Reload Apache
          service: name=httpd state=reloaded

        - name: Restart firewalld
          service: name=firewalld state=restarted
