---
- include_vars: roles/lampserver/vars/main.yml

- name: Delete anonymous users for ansible
  action: mysql_user user="" host="{{ ansible_hostname }}" state="absent"

- name: Delete anonymous users
  action: mysql_user user="" state="absent"

- name: Remove test database
  action: mysql_db db=test state=absent

- name: Set MySQL Root Password
  mysql_user: user=root host={{ item }} password={{ mysql_root_password }} priv=*.*:ALL,GRANT state=present
  with_items:
#    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: copy .my.cnf file with root password credentials
  template:
    src: roles/lampserver/templates/my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600
